version: '3.8'

services:
  eora_redis:
    image: redis:7-alpine
    container_name: eora_redis
    volumes:
      - redisdata:/data
    restart: always
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    env_file:
      - .env
    ports:
      - "6380:6379"

  eora_qapi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: eora_qapi
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - eora_redis
    restart: unless-stopped

volumes:
  redisdata: